# volumes have been created to make sure the data doesnt get wiped away even though the compose is restarted
# run docker-compose up to start it
#  install pip, psycopg-binary, python3
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "81:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always 

  apache2:
    image: httpd:latest
    container_name: apache2_container
    ports: 
      - "82:80"
    restart: always


  script_runner:
    image: ubuntu:20.04
    container_name: script_runner
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: /home/anirudh-s-space/sysad tasks
        target: /sysad
    tty: true
    stdin_open: true
    command: bash -c "apt-get update && apt-get install python3 && apt-get install nano && apt-get install pip && pip install psycopg2-binary && tail -f /dev/null"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


volumes:
  postgres_data: